version: 2.1

jobs:
  move-along:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: "It's ok"
          command: |
            echo "#######"
            echo "#        #    #  ######  #####    #   #   #####  #    #     #    #    #   ####"
            echo "#        #    #  #       #    #    # #      #    #    #     #    ##   #  #    #"
            echo "#####    #    #  #####   #    #     #       #    ######     #    # #  #  #"
            echo "#        #    #  #       #####      #       #    #    #     #    #  # #  #  ###"
            echo "#         #  #   #       #   #      #       #    #    #     #    #   ##  #    #"
            echo "#######    ##    ######  #    #     #       #    #    #     #    #    #   ####"
            echo
            echo "    #     ####"
            echo "    #    #"
            echo "    #     ####"
            echo "    #         #"
            echo "    #    #    #"
            echo "    #     ####"
            echo
            echo "                  ###"
            echo "  ####   #    #   ###"
            echo " #    #  #   #    ###"
            echo " #    #  ####      #"
            echo " #    #  #  #"
            echo " #    #  #   #    ###"
            echo "  ####   #    #   ###"

workflows:
  nothing-to-see-here:
    jobs:
      - move-along